@extends('layouts.Accueil.liens')

<div class="forcefullwidth_wrapper_tp_banner" id="rev_slider_1014_1_forcefullwidth" style="position:relative;width:100%;height:auto;margin-top:0px;margin-bottom:0px"><div id="rev_slider_1014_1_wrapper" class="rev_slider_wrapper ms-hero-rev fullscreen-container" data-alias="typewriter-effect" data-source="gallery" style="background-color: transparent; padding: 0px; margin-top: 0px; margin-bottom: 0px; position: absolute; max-height: none; overflow: visible; height: 214px; width: 1349px; left: 0px;">
    <!-- START REVOLUTION SLIDER 5.3.0.2 fullscreen mode -->
    <div id="rev_slider_1014_1" class="rev_slider fullscreenbanner revslider-initialised tp-simpleresponsive" style="max-height: none; margin-top: 0px; margin-bottom: 0px; height: 100%;" data-version="5.3.0.2" data-slideactive="rs-2800">
      <ul class="tp-revslider-mainul" style="visibility: visible; display: block; overflow: hidden; width: 100%; height: 100%; max-height: none;">
        <!-- SLIDE  -->
        <li data-index="rs-2800" data-transition="slidingoverlayhorizontal" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="assets/img/demo/back_video_100x50.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli rs-pause-timer-always active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 20; visibility: inherit; opacity: 1; background-color: rgba(255, 255, 255, 0);">
          <!-- MAIN IMAGE -->
          <div class="slotholder" style="position: absolute; top: 0px; left: 0px; z-index: 0; width: 100%; height: 100%; visibility: inherit; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="assets/img/demo/back_video.jpg" alt="" data-bgposition="center center" data-bgfit="cover" class="rev-slidebg defaultimg" data-no-retina="">--><div class="rs-background-video-layer defaultvid HasListener" data-forcerewind="on" data-volume="mute" data-videowidth="100%" data-videoheight="100%" data-videomp4="assets/media/back_video.mp4" data-videopreload="auto" data-videoloop="loop" data-forcecover="1" data-aspectratio="16:9" data-autoplay="true" data-autoplayonlyfirsttime="false" style="z-index: 30; left: 0px; top: 0px; transform: matrix(1, 0, 0, 1, 0, 0); visibility: inherit; opacity: 1;"><div class="html5vid fullcoveredvideo" style="position:relative;top:0px;left:0px;width:100%;height:100%; overflow:hidden;"><video style="object-fit: cover; background-size: cover; width: 100%; height: 354.585%; visibility: inherit; opacity: 1; position: absolute; left: 0px; top: -127.293%; display: block;" class="resizelistener" loop="" preload="auto"><source src="assets/media/back_video.mp4" type="video/mp4"></video></div><div class="tp-video-play-button"><i class="revicon-right-dir"></i><span class="tp-revstop">&nbsp;</span></div><div class="rs-fullvideo-cover"></div></div><div class="tp-bgimg defaultimg " style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;assets/img/demo/back_video.jpg&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; z-index: 20; visibility: inherit; position: inherit; transform: matrix(1, 0, 0, 1, 0, 0);" src="assets/img/demo/back_video.jpg"></div></div>
          <!-- LAYERS -->
          <!-- BACKGROUND VIDEO LAYER -->

          <!-- LAYER NR. 1 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 0px; top: 0px; z-index: 5;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption tp-shape tp-shapewrapper " id="slide-2800-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;from&quot;:&quot;opacity:0;&quot;,&quot;speed&quot;:500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:0,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;speed&quot;:5000,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; background-color: rgba(0, 0, 0, 0.5); border-color: rgba(0, 0, 0, 0); border-width: 0px; visibility: inherit; transition: none 0s ease 0s; text-align: left; line-height: 26px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 15px; white-space: nowrap; min-height: 214px; min-width: 1349px; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"> </div></div></div></div>
          <!-- LAYER NR. 2 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 589px; top: 71px; z-index: 6;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption   tp-resizeme" id="slide-2800-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-80','-80','-130','-157']" data-fontsize="['130','130','100','80']" data-lineheight="['130','130','100','80']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;sX:1;sY:1;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 32px; line-height: 32px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; border-width: 0px; letter-spacing: -2px; visibility: inherit; transition: none 0s ease 0s; text-align: center; margin: 0px; padding: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">Web Agency </div></div></div></div>
          <!-- LAYER NR. 3 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 667px; top: 110px; z-index: 7;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-2800-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['16','16','-54','-89']" data-width="60" data-height="3" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7; background-color: rgb(3, 169, 244); border-color: rgba(0, 0, 0, 0); border-width: 0px; visibility: inherit; transition: none 0s ease 0s; text-align: left; line-height: 6px; margin: 0px; padding: 0px; letter-spacing: 0px; font-weight: 400; font-size: 4px; white-space: nowrap; min-height: 1px; min-width: 15px; max-height: 1px; max-width: 15px; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;"> </div></div></div></div>
          <!-- LAYER NR. 4 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 593px; top: 118px; z-index: 8;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption   tp-resizeme" id="slide-2800-layer-2" data-x="['center','center','center','center']" data-hoffset="['-10','-10','-10','-10']" data-y="['middle','middle','middle','middle']" data-voffset="['65','65','-8','-32']" data-fontsize="['40','40','30','30']" data-width="['640','640','480','360']" data-height="none" data-whitespace="['nowrap','nowrap','normal','normal']" data-type="text" data-typewriter="{&quot;lines&quot;:&quot;167%20Clients%20Worldwide.,23%20Qualified%20Employees.,150%20Cups%20of%20Coffee%20per%20Day.&quot;,&quot;enabled&quot;:&quot;on&quot;,&quot;speed&quot;:&quot;60&quot;,&quot;delays&quot;:&quot;1%7C100&quot;,&quot;looped&quot;:&quot;on&quot;,&quot;cursorType&quot;:&quot;one&quot;,&quot;blinking&quot;:&quot;on&quot;,&quot;word_delay&quot;:&quot;off&quot;,&quot;sequenced&quot;:&quot;on&quot;,&quot;hide_cursor&quot;:&quot;off&quot;,&quot;start_delay&quot;:&quot;1500&quot;,&quot;newline_delay&quot;:&quot;1000&quot;,&quot;deletion_speed&quot;:&quot;20&quot;,&quot;deletion_delay&quot;:&quot;1000&quot;,&quot;blinking_speed&quot;:&quot;500&quot;,&quot;linebreak_delay&quot;:&quot;60&quot;,&quot;cursor_type&quot;:&quot;two&quot;,&quot;background&quot;:&quot;off&quot;}" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;sX:1;sY:1;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8; min-width: 158px; max-width: 158px; white-space: nowrap; font-size: 10px; line-height: 10px; font-weight: 300; color: rgb(255, 255, 255); font-family: Roboto, sans-serif; border-width: 0px; visibility: inherit; transition: none 0s ease 0s; text-align: center; margin: 0px; padding: 0px; letter-spacing: 0px; min-height: 0px; max-height: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;" data-typewriter-sequenced="true">Dedicated. Inspired. Passio</div></div></div></div>
          <!-- LAYER NR. 5 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 612px; top: 160px; z-index: 9;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption rev-btn tp-resizeme tp-withaction rs-hover-ready" id="slide-2800-layer-4" data-x="['right','right','center','center']" data-hoffset="['660','550','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['240','240','100','83']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;scrollbelow&quot;,&quot;offset&quot;:&quot;px&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;150&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 0);bw:2px 2px 2px 2px;&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[50,50,50,50]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[50,50,50,50]" style="z-index: 9; white-space: nowrap; font-size: 4px; line-height: 11px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-color: rgba(255, 255, 255, 0.25); border-style: solid; border-width: 0px; border-radius: 4px; outline: none; box-shadow: none; box-sizing: border-box; letter-spacing: 1px; cursor: pointer; visibility: inherit; transition: none 0s ease 0s; text-align: left; margin: 0px; padding: 0px 12px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">ABOUT US </div></div></div></div>
          <!-- LAYER NR. 6 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 672px; top: 162px; z-index: 10;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption   tp-resizeme" id="slide-2800-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['237','237','158','141']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10; white-space: nowrap; font-size: 6px; line-height: 6px; font-weight: 300; color: rgb(255, 255, 255); font-family: Roboto, sans-serif; border-width: 0px; visibility: inherit; transition: none 0s ease 0s; text-align: left; margin: 0px; padding: 0px; letter-spacing: 0px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">or </div></div></div></div>
          <!-- LAYER NR. 7 -->
          <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 684px; top: 160px; z-index: 11;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption rev-btn tp-resizeme tp-withaction rs-hover-ready" id="slide-2800-layer-5" data-x="['left','left','center','center']" data-hoffset="['660','550','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['240','240','224','207']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;scrollbelow&quot;,&quot;offset&quot;:&quot;px&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;150&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 0);bw:2px 2px 2px 2px;&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[50,50,50,50]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[50,50,50,50]" style="z-index: 11; white-space: nowrap; font-size: 4px; line-height: 11px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-color: rgba(255, 255, 255, 0.25); border-style: solid; border-width: 0px; border-radius: 4px; outline: none; box-shadow: none; box-sizing: border-box; letter-spacing: 1px; cursor: pointer; visibility: inherit; transition: none 0s ease 0s; text-align: left; margin: 0px; padding: 0px 12px; min-height: 0px; min-width: 0px; max-height: none; max-width: none; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">CONTACT </div></div></div></div>
        </li>
        <!-- SLIDE  -->
        <li data-index="rs-2801" data-transition="slidingoverlayhorizontal" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="assets/plugins/revolution/assets/images/citybg-100x50.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli" style="width: 100%; height: 100%; overflow: hidden;">
          <!-- MAIN IMAGE -->
          <div class="slotholder" style="position:absolute; top:0px; left:0px; z-index:0;width:100%;height:100%;"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="assets/plugins/revolution/assets/images/citybg.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg defaultimg" data-no-retina="">--><div class="tp-bgimg defaultimg " style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;assets/plugins/revolution/assets/images/citybg.jpg&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 0;" src="assets/plugins/revolution/assets/images/citybg.jpg"></div></div>
          <!-- LAYERS -->
          <!-- LAYER NR. 8 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption tp-shape tp-shapewrapper " id="slide-2801-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;from&quot;:&quot;opacity:0;&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:0,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12; background-color: rgba(0, 0, 0, 0.5); border-color: rgba(0, 0, 0, 0); border-width: 0px; visibility: hidden;"> </div></div></div></div>
          <!-- LAYER NR. 9 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption   tp-resizeme" id="slide-2801-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-80','-80','-130','-157']" data-fontsize="['130','130','100','80']" data-lineheight="['130','130','100','80']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;sX:1;sY:1;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13; white-space: nowrap; font-size: 130px; line-height: 130px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-width: 0px; letter-spacing: -7px; visibility: hidden;">Dream. Big. </div></div></div></div>
          <!-- LAYER NR. 10 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-2801-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['16','16','-54','-89']" data-width="60" data-height="3" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14; background-color: rgb(3, 169, 244); border-color: rgba(0, 0, 0, 0); border-width: 0px; visibility: hidden;"> </div></div></div></div>
          <!-- LAYER NR. 11 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption   tp-resizeme hide-typewriter-cursor" id="slide-2801-layer-2" data-x="['center','center','center','center']" data-hoffset="['-10','-10','-10','-10']" data-y="['middle','middle','middle','middle']" data-voffset="['65','65','-8','-32']" data-fontsize="['40','40','30','30']" data-width="['640','640','480','360']" data-height="none" data-whitespace="normal" data-type="text" data-typewriter="{&quot;lines&quot;:&quot;Customizable%20Typerwiter%20Effect.,Add%20to%20any%20Text%20Layer.,A%20100%25%20Free%20Addon%20for%20Rvsldr.&quot;,&quot;enabled&quot;:&quot;on&quot;,&quot;speed&quot;:&quot;60&quot;,&quot;delays&quot;:&quot;1%7C100&quot;,&quot;looped&quot;:&quot;on&quot;,&quot;cursorType&quot;:&quot;one&quot;,&quot;blinking&quot;:&quot;on&quot;,&quot;word_delay&quot;:&quot;off&quot;,&quot;sequenced&quot;:&quot;on&quot;,&quot;hide_cursor&quot;:&quot;off&quot;,&quot;start_delay&quot;:&quot;1500&quot;,&quot;newline_delay&quot;:&quot;1000&quot;,&quot;deletion_speed&quot;:&quot;20&quot;,&quot;deletion_delay&quot;:&quot;1000&quot;,&quot;blinking_speed&quot;:&quot;500&quot;,&quot;linebreak_delay&quot;:&quot;60&quot;,&quot;cursor_type&quot;:&quot;two&quot;,&quot;background&quot;:&quot;off&quot;}" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;sX:1;sY:1;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15; min-width: 640px; max-width: 640px; white-space: normal; font-size: 40px; line-height: 40px; font-weight: 300; color: rgb(255, 255, 255); font-family: Roboto, sans-serif; border-width: 0px; visibility: hidden;" data-typewriter-sequenced="true">Made to Captivate your Audience. </div></div></div></div>
          <!-- LAYER NR. 12 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption rev-btn tp-resizeme tp-withaction" id="slide-2801-layer-4" data-x="['right','right','center','center']" data-hoffset="['660','550','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['240','240','100','83']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;scrollbelow&quot;,&quot;offset&quot;:&quot;px&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;150&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 0);bw:2px 2px 2px 2px;&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[50,50,50,50]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[50,50,50,50]" style="z-index: 16; white-space: nowrap; font-size: 15px; line-height: 46px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-color: rgba(255, 255, 255, 0.25); border-style: solid; border-width: 2px; border-radius: 4px; outline: none; box-shadow: none; box-sizing: border-box; letter-spacing: 5px; cursor: pointer; visibility: hidden;">ABOUT US </div></div></div></div>
          <!-- LAYER NR. 13 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption   tp-resizeme" id="slide-2801-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['237','237','158','141']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 17; white-space: nowrap; font-size: 25px; line-height: 25px; font-weight: 300; color: rgb(255, 255, 255); font-family: Roboto, sans-serif; border-width: 0px; visibility: hidden;">or </div></div></div></div>
          <!-- LAYER NR. 14 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption rev-btn tp-resizeme tp-withaction" id="slide-2801-layer-5" data-x="['left','left','center','center']" data-hoffset="['660','550','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['240','240','224','207']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;scrollbelow&quot;,&quot;offset&quot;:&quot;px&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;150&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 0);bw:2px 2px 2px 2px;&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[50,50,50,50]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[50,50,50,50]" style="z-index: 18; white-space: nowrap; font-size: 15px; line-height: 46px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-color: rgba(255, 255, 255, 0.25); border-style: solid; border-width: 2px; border-radius: 4px; outline: none; box-shadow: none; box-sizing: border-box; letter-spacing: 5px; cursor: pointer; visibility: hidden;">CONTACT </div></div></div></div>
        </li>
        <!-- SLIDE  -->
        <li data-index="rs-2802" data-transition="slidingoverlayhorizontal" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="assets/plugins/revolution/assets/images/farmbg-100x50.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli" style="width: 100%; height: 100%; overflow: hidden;">
          <!-- MAIN IMAGE -->
          <div class="slotholder" style="position:absolute; top:0px; left:0px; z-index:0;width:100%;height:100%;"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="assets/img/demo/city_cloud.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg defaultimg" data-no-retina="">--><div class="tp-bgimg defaultimg " style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;assets/img/demo/city_cloud.jpg&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 0;" src="assets/img/demo/city_cloud.jpg"></div></div>
          <!-- LAYERS -->
          <!-- LAYER NR. 15 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption tp-shape tp-shapewrapper " id="slide-2802-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;from&quot;:&quot;opacity:0;&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:0,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 19; background-color: rgba(0, 0, 0, 0.5); border-color: rgba(0, 0, 0, 0); border-width: 0px; visibility: hidden;"> </div></div></div></div>
          <!-- LAYER NR. 16 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption   tp-resizeme hide-typewriter-cursor" id="slide-2802-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-80','-81','-171','-146']" data-fontsize="['100','100','70','60']" data-lineheight="['100','100','70','50']" data-width="['760','760','none','360']" data-height="none" data-whitespace="['normal','normal','nowrap','normal']" data-type="text" data-typewriter="{&quot;lines&quot;:&quot;&quot;,&quot;enabled&quot;:&quot;on&quot;,&quot;speed&quot;:&quot;80&quot;,&quot;delays&quot;:&quot;1%7C100&quot;,&quot;looped&quot;:&quot;off&quot;,&quot;cursorType&quot;:&quot;one&quot;,&quot;blinking&quot;:&quot;on&quot;,&quot;word_delay&quot;:&quot;off&quot;,&quot;sequenced&quot;:&quot;off&quot;,&quot;hide_cursor&quot;:&quot;on&quot;,&quot;start_delay&quot;:&quot;1000&quot;,&quot;newline_delay&quot;:&quot;1000&quot;,&quot;deletion_speed&quot;:&quot;20&quot;,&quot;deletion_delay&quot;:&quot;1000&quot;,&quot;blinking_speed&quot;:&quot;500&quot;,&quot;linebreak_delay&quot;:&quot;60&quot;,&quot;cursor_type&quot;:&quot;two&quot;,&quot;background&quot;:&quot;off&quot;}" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;sX:1;sY:1;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:500,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 20; min-width: 760px; max-width: 760px; white-space: normal; font-size: 100px; line-height: 100px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; border-width: 0px; letter-spacing: -5px; visibility: hidden;">It Always Seems<br>Impossible<br> Until its Done. </div></div></div></div>
          <!-- LAYER NR. 17 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-2802-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['96','96','-35','-19']" data-width="60" data-height="3" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:5000,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 21; background-color: rgb(3, 169, 244); border-color: rgba(0, 0, 0, 0); border-width: 0px; visibility: hidden;"> </div></div></div></div>
          <!-- LAYER NR. 18 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption   tp-resizeme" id="slide-2802-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['144','144','12','18']" data-fontsize="['40','40','30','30']" data-width="['640','640','480','360']" data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;sX:1;sY:1;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:5000,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 22; min-width: 640px; max-width: 640px; white-space: normal; font-size: 40px; line-height: 40px; font-weight: 300; color: rgb(255, 255, 255); font-family: Roboto, sans-serif; border-width: 0px; visibility: hidden;">Nelson Mandela </div></div></div></div>
          <!-- LAYER NR. 19 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption rev-btn tp-resizeme tp-withaction" id="slide-2802-layer-4" data-x="['right','right','center','center']" data-hoffset="['660','550','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['240','240','100','93']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;scrollbelow&quot;,&quot;offset&quot;:&quot;px&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:5000,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;150&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 0);bw:2px 2px 2px 2px;&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[50,50,50,50]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[50,50,50,50]" style="z-index: 23; white-space: nowrap; font-size: 15px; line-height: 46px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-color: rgba(255, 255, 255, 0.25); border-style: solid; border-width: 2px; border-radius: 4px; outline: none; box-shadow: none; box-sizing: border-box; letter-spacing: 5px; cursor: pointer; visibility: hidden;">ABOUT US </div></div></div></div>
          <!-- LAYER NR. 20 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption   tp-resizeme" id="slide-2802-layer-6" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['237','237','158','151']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:5000,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 24; white-space: nowrap; font-size: 25px; line-height: 25px; font-weight: 300; color: rgb(255, 255, 255); font-family: Roboto, sans-serif; border-width: 0px; visibility: hidden;">or </div></div></div></div>
          <!-- LAYER NR. 21 -->
          <div class="tp-parallax-wrap " style="position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption rev-btn tp-resizeme tp-withaction" id="slide-2802-layer-5" data-x="['left','left','center','center']" data-hoffset="['660','550','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['240','240','224','217']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;scrollbelow&quot;,&quot;offset&quot;:&quot;px&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;speed&quot;:2500,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:5000,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;150&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(0, 0, 0, 1.00);bg:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 0);bw:2px 2px 2px 2px;&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[50,50,50,50]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[50,50,50,50]" style="z-index: 25; white-space: nowrap; font-size: 15px; line-height: 46px; font-weight: 700; color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif; background-color: rgba(0, 0, 0, 0); border-color: rgba(255, 255, 255, 0.25); border-style: solid; border-width: 2px; border-radius: 4px; outline: none; box-shadow: none; box-sizing: border-box; letter-spacing: 5px; cursor: pointer; visibility: hidden;">CONTACT </div></div></div></div>
        </li>
      </ul>
      <div class="tp-bannertimer tp-bottom" style="visibility: hidden; width: 0%;"></div>
    <div class="tp-loader off" style="display: none;"><div class="dot1"></div><div class="dot2"></div><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div><div class="tp-leftarrow tparrows uranus noSwipe" style="top: 50%; transform: matrix(1, 0, 0, 1, 20, -25); left: 0px;"></div><div class="tp-rightarrow tparrows uranus noSwipe" style="top: 50%; transform: matrix(1, 0, 0, 1, -70, -25); left: 100%;"></div></div>
  </div><div class="tp-fullwidth-forcer" style="width: 100%; height: 214px;"></div></div>
  <script>
    (function(i, s, o, g, r, a, m)
    {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function()
      {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-90917746-2', 'auto');
    ga('send', 'pageview');
  </script>
  <script type="text/javascript">
    $(function()
    {
      $('#Container').mixItUp();
    });
    var tpj = jQuery;
    var revapi1014;
    tpj(document).ready(function()
    {
      if (tpj("#rev_slider_1014_1").revolution == undefined)
      {
        revslider_showDoubleJqueryError("#rev_slider_1014_1");
      }
      else
      {
        revapi1014 = tpj("#rev_slider_1014_1").show().revolution(
        {
          sliderType: "standard",
          jsFileLocation: "assets/plugins/revolution/revolution/js/",
          sliderLayout: "fullscreen",
          dottedOverlay: "none",
          delay: 9000,
          navigation:
          {
            keyboardNavigation: "off",
            keyboard_direction: "horizontal",
            mouseScrollNavigation: "off",
            mouseScrollReverse: "default",
            onHoverStop: "off",
            touch:
            {
              touchenabled: "on",
              swipe_threshold: 75,
              swipe_min_touches: 1,
              swipe_direction: "horizontal",
              drag_block_vertical: false
            },
            arrows:
            {
              style: "uranus",
              enable: true,
              hide_onmobile: true,
              hide_under: 768,
              hide_onleave: false,
              tmp: '',
              left:
              {
                h_align: "left",
                v_align: "center",
                h_offset: 20,
                v_offset: 0
              },
              right:
              {
                h_align: "right",
                v_align: "center",
                h_offset: 20,
                v_offset: 0
              }
            }
          },
          responsiveLevels: [1240, 1024, 778, 480],
          visibilityLevels: [1240, 1024, 778, 480],
          gridwidth: [1240, 1024, 778, 480],
          gridheight: [868, 768, 960, 600],
          lazyType: "none",
          shadow: 0,
          spinner: "off",
          stopLoop: "on",
          stopAfterLoops: 0,
          stopAtSlide: 1,
          shuffle: "off",
          autoHeight: "off",
          fullScreenAutoWidth: "off",
          fullScreenAlignForce: "off",
          fullScreenOffsetContainer: "",
          fullScreenOffset: "60px",
          disableProgressBar: "on",
          hideThumbsOnMobile: "off",
          hideSliderAtLimit: 0,
          hideCaptionAtLimit: 0,
          hideAllCaptionAtLilmit: 0,
          debugMode: false,
          fallbacks:
          {
            simplifyAll: "off",
            nextSlideOnWindowFocus: "off",
            disableFocusListener: false,
          }
        });
      }
      RsTypewriterAddOn(tpj, revapi1014);
    }); /*ready*/
  </script>
